# Function to compute 5/0 and use try/except to catch the exceptions

In [3]:
def ZeroDivide( ):
    try:
        result = 5/0
    except Exception as e:
        print("Error : ", e)

ZeroDivide()

Error :  division by zero


# Python program to generate all sentences from lists

In [3]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for subject in subjects:
    for verb in verbs:
        for object in objects:
            print(subject + " " + verb + " " + object + ".")

Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Vandermonde Matrix

In [1]:
import numpy as np

def generate_vandermonde_matrix(input_vector,number_of_columns,increasing_order=False):
    n = number_of_columns
    if not increasing_order:
        output_matrix = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size, n)
    elif increasing_order:
        output_matrix = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size, n)
    
    return output_matrix

input_vector = np.array([1,2,3,4,5])
number_of_columns = 3


print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",number_of_columns,"\n")

output_matrix = generate_vandermonde_matrix(input_vector,number_of_columns,False)
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_matrix,"\n")

output_matrix = generate_vandermonde_matrix(input_vector,number_of_columns,True)
print("Vander matrix of the input array in increasing order of powers:\n\n",output_matrix,"\n")

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

